services:
  - type: web
    name: annotateai-backend
    runtime: python
    region: frankfurt
    plan: free
    buildCommand: "pip install --no-cache-dir -r requirements.txt"
    startCommand: "gunicorn run:app --workers 1 --threads 2 --timeout 120 --bind 0.0.0.0:$PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.5
      - key: MONGO_URI
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: JWT_SECRET_KEY
        generateValue: true
